spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.gcu.todoserver.pojo

logging:
  level:
    com:
      gcu:
        todoserver:
          mapper:
            debug
